Update build_and_publish.yml

diff --git a/.github/workflows/build_and_publish.yml b/.github/workflows/build_and_publish.yml
--- a/.github/workflows/build_and_publish.yml
+++ b/.github/workflows/build_and_publish.yml
@@ -11,75 +11,83 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  build-and-push-image:
+  migrate:
     name: Build and push
     runs-on: [self-hosted, Linux]
     permissions:
       contents: read
       packages: write
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-          tags: |
-            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
-            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
-            type=raw,value=test,enable=true
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          build-args: |
-            APP_VERSION=${{ github.ref_name }}
-
-  migrate:
-    name: Pull new version and make migration
-    runs-on: [self-hosted, Linux]
-    needs: build-and-push-image
-    environment:
-      name: Pre-release
     env:
-      CONTAINER_NAME: com_profcomff_dwh_definitions_test
       DB_DSN: "postgresql://postgres:12345@192.168.1.6:5432/definitions"
+
     steps:
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Pull new version
-        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
-
-      - name: Run new version
-        id: run_test
-        run: |
-          docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true
-          docker run \
-            --detach \
-            --restart on-failure:3 \
-            --network=web -p 8080:8080 \
-            --env AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${{ secrets.SQL_ALCHEMY_CONN }} \
-            --name ${{ env.CONTAINER_NAME }} \
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Log in to the Container registry
+#        uses: docker/login-action@v2
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Extract metadata (tags, labels) for Docker
+#        id: meta
+#        uses: docker/metadata-action@v4
+#        with:
+#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+#          tags: |
+#            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
+#            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
+#            type=raw,value=test,enable=true
+#
+#      - name: Build and push Docker image
+#        uses: docker/build-push-action@v4
+#        with:
+#          context: .
+#          push: true
+#          tags: ${{ steps.meta.outputs.tags }}
+#          labels: ${{ steps.meta.outputs.labels }}
+#          build-args: |
+#            APP_VERSION=${{ github.ref_name }}
+      - name: migrate
+        run: docker run \
+             -v $(pwd):/app \
+             -e DB_DSN=postgresql://localhost:5432/dwh \
+             --rm \
+             python \
+             /bin/bash -c 'python -m ensurepip && cd /app && pip install -r requirements.txt -r requirements.dev.txt && alembic upgrade head'
+#  migrate:
+#    name: Pull new version and make migration
+#    runs-on: [self-hosted, Linux]
+#    needs: build-and-push-image
+#    environment:
+#      name: Pre-release
+#    env:
+#      CONTAINER_NAME: com_profcomff_dwh_definitions_test
+#      DB_DSN: "postgresql://postgres:12345@192.168.1.6:5432/definitions"
+#    steps:
+#      - name: Log in to the Container registry
+#        uses: docker/login-action@v2
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Pull new version
+#        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
+#
+#      - name: Run new version
+#        id: run_test
+#        run: |
+#          docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true
+#          docker run \
+#            --detach \
+#            --restart on-failure:3 \
+#            --network=web -p 8080:8080 \
+#            --env AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${{ secrets.SQL_ALCHEMY_CONN }} \
+#            --name ${{ env.CONTAINER_NAME }} \
+#            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
 
   build-and-publish:
     name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
